"""Add index to submissions.created_at

Revision ID: 070c65eece9d
Revises: 4aadbca55652
Create Date: 2026-07-09 17:12:43.574389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '070c65eece9d'
down_revision: Union[str, Sequence[str], None] = '4aadbca55652'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_submissions_created_at'), 'submissions', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_submissions_created_at'), table_name='submissions')
    # ### end Alembic commands ###
