"""Sync DB

Revision ID: 8ee4f17f3df1
Revises: 070c65eece9d
Create Date: 2026-08-25 18:35:09.469951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ee4f17f3df1'
down_revision: Union[str, Sequence[str], None] = '070c65eece9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_contest_participant', 'contest_participants', ['contest_id', 'user_id'])
    op.create_foreign_key(None, 'contest_participants', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'contest_participants', 'contests', ['contest_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_contest_problems_problem_id'), 'contest_problems', ['problem_id'], unique=False)
    op.create_foreign_key(None, 'contest_problems', 'problems', ['problem_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'contest_problems', 'contests', ['contest_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'contests', 'users', ['created_by'], ['id'], ondelete='CASCADE')
    op.add_column('problems', sa.Column('category', sa.String(length=100), nullable=True))
    op.add_column('submissions', sa.Column('ai_review', sa.Text(), nullable=True))
    op.add_column('submissions', sa.Column('is_sample_only', sa.Boolean(), server_default='false', nullable=False))
    op.create_index(op.f('ix_submissions_created_at'), 'submissions', ['created_at'], unique=False)
    op.create_index(op.f('ix_submissions_is_sample_only'), 'submissions', ['is_sample_only'], unique=False)
    op.create_index(op.f('ix_submissions_verdict'), 'submissions', ['verdict'], unique=False)
    op.create_foreign_key(None, 'submissions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'submissions', 'problems', ['problem_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'test_cases', 'problems', ['problem_id'], ['id'], ondelete='CASCADE')
    op.add_column('users', sa.Column('full_name', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('phone_number', sa.String(length=30), nullable=True))
    op.add_column('users', sa.Column('google_id', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('github_id', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('users', sa.Column('is_verified', sa.Boolean(), server_default='false', nullable=False))
    op.add_column('users', sa.Column('profile_picture', sa.Text(), nullable=True))
    op.add_column('users', sa.Column('date_of_birth', sa.String(length=20), nullable=True))
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.create_index(op.f('ix_users_github_id'), 'users', ['github_id'], unique=True)
    op.create_index(op.f('ix_users_google_id'), 'users', ['google_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_google_id'), table_name='users')
    op.drop_index(op.f('ix_users_github_id'), table_name='users')
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.drop_column('users', 'date_of_birth')
    op.drop_column('users', 'profile_picture')
    op.drop_column('users', 'is_verified')
    op.drop_column('users', 'is_admin')
    op.drop_column('users', 'github_id')
    op.drop_column('users', 'google_id')
    op.drop_column('users', 'phone_number')
    op.drop_column('users', 'full_name')
    op.drop_constraint(None, 'test_cases', type_='foreignkey')
    op.drop_constraint(None, 'submissions', type_='foreignkey')
    op.drop_constraint(None, 'submissions', type_='foreignkey')
    op.drop_index(op.f('ix_submissions_verdict'), table_name='submissions')
    op.drop_index(op.f('ix_submissions_is_sample_only'), table_name='submissions')
    op.drop_index(op.f('ix_submissions_created_at'), table_name='submissions')
    op.drop_column('submissions', 'is_sample_only')
    op.drop_column('submissions', 'ai_review')
    op.drop_column('problems', 'category')
    op.drop_constraint(None, 'contests', type_='foreignkey')
    op.drop_constraint(None, 'contest_problems', type_='foreignkey')
    op.drop_constraint(None, 'contest_problems', type_='foreignkey')
    op.drop_index(op.f('ix_contest_problems_problem_id'), table_name='contest_problems')
    op.drop_constraint(None, 'contest_participants', type_='foreignkey')
    op.drop_constraint(None, 'contest_participants', type_='foreignkey')
    op.drop_constraint('uq_contest_participant', 'contest_participants', type_='unique')
    # ### end Alembic commands ###
